services:
  app:
    build: .
    command: sh -c "ng serve --host 0.0.0.0 --poll 1000"
    ports:
      - 4200:4200
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
volumes:
  node_modules: